development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: restaurant_booking_development
  pool: 5
  username: arvi
  password: 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: restaurant_booking_test
  username: arvi
  pool: 5
  password: 
  host: localhost
  port: 5432